---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwenpaw-workspace
  namespace: qwenpaw
  labels:
    app.kubernetes.io/name: qwenpaw
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 10Gi
