---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: skillshub
  namespace: skillshub
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skillshub
  namespace: skillshub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: skillshub
subjects:
  - kind: ServiceAccount
    name: skillshub
    namespace: skillshub
