---
apiVersion: v1
kind: Secret
metadata:
  name: hiclaw-secrets
  namespace: hiclaw
  labels:
    app.kubernetes.io/name: hiclaw
  annotations:
    vault.hashicorp.com/managed: "true"
type: Opaque
stringData:
  AGENT_API_KEY: "CHANGE-ME"
  OPENCLAW_API_KEY: "CHANGE-ME"
  NEMOCLAW_API_KEY: "CHANGE-ME"
  QWENPAW_API_KEY: "CHANGE-ME"
  REME_API_KEY: "CHANGE-ME"
  SKILLSHUB_API_KEY: "CHANGE-ME-from-vault"
