---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hiclaw
  namespace: hiclaw
  labels:
    app.kubernetes.io/name: hiclaw
    app.kubernetes.io/part-of: autonomous-ai-agents
  annotations:
    vault.hashicorp.com/role: "hiclaw"
